# Mimetype list taken from Chromium
# https://cs.chromium.org/chromium/src/net/base/mime_util.cc?q=%22audio/mp3%22&sq=package:chromium&dr=C&l=155

# Other sources include:
# https://github.com/learningequality/kolibri/blob/26073dda2569bb38bfe1e08ba486e96f650d10ce/kolibri/core/content/constants/mime.types
# mimetypes library (gives mp2 for mpeg files, which is wierd)

# 
 
mime = {
    "video/webm": "webm",
    "application/wasm": "wasm",
    "application/x-chrome-extension": "crx",
    "application/xhtml+xml": "xhtml",
    "audio/flac": "flac",
    "audio/mp3": "mp3",
    "audio/ogg": "ogg",
    "audio/wav": "wav",
    "audio/webm": "webm",
    "audio/x-m4a": "m4a",
    "image/gif": "gif",
    "image/jpeg": "jpeg",
    "image/png": "png",
    "image/apng": "png",
    "image/webp": "webp",
    "multipart/related": "mht",
    "text/css": "css",
    "text/html": "html",
    "text/javascript": "js",
    "text/xml": "xml",
    "video/mp4": "mp4",
    "video/ogg": "ogv",
    "image/x-icon": "ico",
    "application/epub+zip": "epub",
    "application/font-woff": "woff",
    "application/gzip": "gz",
    "application/javascript": "js",
    "application/json": "json",
    "application/octet-stream": "bin",
    "application/pdf": "pdf",
    "application/pkcs7-mime": "p7m",
    "application/pkcs7-signature": "p7s",
    "application/postscript": "ps",
    "application/rdf+xml": "rdf",
    "application/rss+xml": "rss",
    "application/vnd.android.package-archive": "apk",
    "application/vnd.mozilla.xul+xml": "xul",
    "application/x-gzip": "gz",
    "application/x-mpegurl": "m3u8",
    "application/x-shockwave-flash": "swf",
    "application/x-tar": "tar",
    "application/zip": "zip",
    "audio/mpeg": "mp3",
    "audio/webm": "weba",
    "image/bmp": "bmp",
    "image/jpeg": "jfif",
    "image/svg+xml": "svg",
    "image/tiff": "tiff",
    "image/vnd.microsoft.icon": "ico",
    "image/x-png": "png",
    "image/x-xbitmap": "xbm",
    "message/rfc822": "eml",
    "text/calendar": "ics",
    "text/html": "ehtml",
    "text/plain": "txt",
    "text/x-sh": "sh",
    "text/xml": "xsl",
    "video/mpeg": "mpeg"}
